Restructure project
boardengineer/scumthespire pull request #11
Opened 2022-03-23 18:27 UTC by BSchneppe

as discussed on discord, i split the mod into 3 modules.

SilentLogger was removed in favour of using commandline options:
.i.e.
`-Droot.log.level=ERROR -Dlog4j.configurationFile=none.xml`

this removes the need for vm options likeisServer or isClient and we can separate server specific changes in to the server module.

2022-03-23 18:44 UTC, boardengineer commented
Too many random refactors and do nothing changes

2022-03-23 19:48 UTC, boardengineer requested changes
Pretty good overall

2022-03-23 19:48 UTC, boardengineer commented on client/src/main/java/autoplay/battleaimod/client/BattleAiClientMod.java
> +package autoplay.battleaimod.client;
I think i got 'autoplay' from either some test mod or com mod or just a random idea i had that i don't want to keep to.  I guess if i needed a real prefix for myself it would net.boardengineer

2022-03-23 19:48 UTC, boardengineer commented on client/src/main/java/autoplay/battleaimod/client/networking/AiClient.java
> +        sendState(DEFAULT_NUM_TURNS);
I don't hate it but it doesn't really belong with the PR, please revert

2022-03-23 19:48 UTC, boardengineer commented on client/src/main/java/autoplay/battleaimod/client/networking/AiClient.java
> +                socket.connect(new InetSocketAddress(HOST_IP, Constants.PORT_NUMBER));
"Constant[s]" files are a design antipattern and rough for discoverability, also they shouldn't be constants but that's an issue for another day.  Really not sure what to do now but this is basically my last choice

2022-03-23 19:48 UTC, boardengineer commented on core/src/main/java/autoplay/battleaimod/core/networking/Constants.java
> +public class Constants {
so the core package exists for these two shared constants files and my random experimental code?  That's odd.

- The Edit Relics and edit card hooks should probably be in here, I assume this would break the card spawning effects otherwise
- There is a lot of code that's effectively mirrored in AiServer/AiClientl; I'd probably the bulk of that logic here

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/BattleAiServerMod.java
> +    public static ArrayList<Comparator<AbstractCard>> cardPlayHeuristics = new ArrayList<>();
counterintuitively, I think the heuristics should go into the core module so they can more easily interact with mod state extneions

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/BattleAiServerMod.java
> +        CardLibrary.cards.remove(Weave.ID);
This must certainly cause problems if its only removed by the server

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/battleai/BattleAiController.java
> +                if (bestTurn != null) {
revert?

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/battleai/BattleAiController.java
> -            FileWriter writer = new FileWriter("out.dot");
Please revert, some changes are fine but it doesn't really belong with these changes

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/battleai/BattleAiController.java
> +    private void writeChildCommand(FileWriter writer, TurnNode node, TurnNode child) {
Tirade:

This helper method is from the "all helper methods are good" school of programming.  but its probably just worse this way, the signature doesn't really describe what it does, it has repeated parameters, the fact that you have to pass in a writer every time is also a bit of a design smell.

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/networking/AiServer.java
> +        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
Does adding a delay help something?

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/networking/AiServer.java
> +                BattleAiServerMod.battleAiController = null;
why clear out the battle ai controller?

2022-03-23 19:48 UTC, boardengineer commented on core/src/main/java/autoplay/battleaimod/core/networking/MessageType.java
> +    DONE,
One of these thing is not like the others, DONE isn't the same type of thing as the other two. granted my protocol is pretty messy as it is but this feels like a step in the wrong directions

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/BattleAiServerMod.java
> +    public void receiveEditRelics() {
this probably needs to be shared

2022-03-23 19:48 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/BattleAiServerMod.java
> +    public void receivePostUpdate() {
... Apparently I've been starting the server both before and after update, I can't imagine it matters but one of them should probably go [The things you notice when you remove a bunch of code from the middle]

2022-03-23 20:10 UTC, BSchneppe commented on server/src/main/java/autoplay/battleaimod/server/battleai/BattleAiController.java
> +                if (bestTurn != null) {
bestTurn can be null here if curTurn == null ? revert regardless?

2022-03-24 07:21 UTC, boardengineer commented on server/src/main/java/autoplay/battleaimod/server/battleai/BattleAiController.java
> +                if (bestTurn != null) {
yes, something's off here but that's not the solution

2022-03-24 07:45 UTC, boardengineer commented on client/src/main/java/autoplay/battleaimod/client/BattleAiClientMod.java
> -    public static boolean isClient;
I need this back, i was using to distinguish between a use-run client and a client running on the cloud where i can't set options

2022-03-24 07:45 UTC, boardengineer commented on client/src/main/resources/ModTheSpire.json
> -}
revert random new line please

2022-03-24 07:45 UTC, boardengineer commented on client/src/main/java/autoplay/battleaimod/client/battleai/CommandRunnerController.java
> -    public HashMap<String, Long> runTimes;
revert reodering?

2022-03-24 08:49 UTC, boardengineer commented on client/src/main/java/autoplay/battleaimod/client/BattleAiClientMod.java
> -        ReflectionHacks.setPrivateStaticFinal(MummifiedHand.class, "logger", new SilentLogger());
Revert all logger changes please

2022-03-24 08:49 UTC, boardengineer commented on core/pom.xml
> +    <artifactId>core</artifactId>
Lets go with BattleAiModCore / BattleAiModServer / BattleAiModClient for id

2022-03-24 08:49 UTC, boardengineer commented on client/pom.xml
> +        <finalName>${project.parent.artifactId}-${project.artifactId}-${project.version}</finalName>
lets just hard code to BattleAiModServer.jar and BattleAiModClient.jar

2024-11-27 15:30 UTC, closed without merging